name: 子域注册申请
description: 在这里提交申请, 以注册 xxx.fucksc.cf 子域(如果需要在您注册的子域上继续注册 456789 级子域, 请在原 issue 发表评论并 @dsy4567)
title: "子域注册申请 [您的 GitHub/洛谷用户名]"
labels: 子域注册申请
assignees:
  - dsy4567
body:
  - type: dropdown
    id: type
    attributes:
      label: 类型
      multiple: true
      options:
        - A
        - AAAA
        - CNAME
        - TXT(吃灰)
        - 跳转至自定义 url
    validations:
      required: true
  - type: input
    id: value
    attributes:
      label: 值
      description: IP 地址/CNAME 域名/TXT 记录值/自定义 url
      placeholder: e.g. 123.132.231/baidu.com/I f*** CCF/https://example.com
    validations:
      required: true
  - type: textarea
    id: notice
    attributes:
      label: 其他说明
    validations:
      required: false
